### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by lefmarna** [lefmarna/protospace-35067#1]
# URL
https://protospace-35067.herokuapp.com/

**Comment by checker-ms** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が引き続き見受けられましたので修正をお願いします！

[現状]
①フォームを空のまま投稿しようとすると、エラーページが表示されてしまう

[修正箇所]
①フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません

https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by checker-ms** [comment]
改めてのご提出ありがとうございます！
挙動確認させて頂きましたが、問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
